#!/usr/bin/env python
from astropy.io import fits
import os
import shutil

os.chdir(os.path.dirname('/Users/bmalko/Desktop/313data/ut20170110_geminiN/copy/'))


for filename in os.listdir('.'):
    if '.fits' not in filename:
        print('not fits')
        continue

    hdu = fits.open(filename)[0]
    print(filename)

#for some data --> if hdu.header['EXPTYPE'] == 'Object': else IMAGETYP object else OBSTYPE
    if hdu.header['OBSTYPE'].strip() == 'OBJECT':
        obj_name = hdu.header['OBJECT'].replace(' ','')
        print('object')
        try:
            os.mkdir(obj_name)
        except OSError:
            print ("Creation of the directory %s failed" % obj_name)
        else:
             print ("Successfully created the directory %s " % obj_name)

        shutil.move(filename, obj_name)
        
